# Installation et importation de pandas
En principe pandas est préinstallé avec la distribution Anconda.
au cas où, il surfit d'exécuter la commande suivante:
```
conda install pandas
```
OU
```
pip install pandas
```
 ou si vous etes sur jupyter ou colab
```
!pip install pandas
```

## Pour l'importation
```
import pandas as pd
```

In [2]:
import pandas as pd

## Modules Associés:
numpy est souvent assoicié à l'utilisation de pandas (matplotlib aussi)

In [3]:
import numpy as np

#Series et DataFrame en Pandas
Les Series, essentiellement des colonnes, les DataFrame<del> s </del> un tableau bidimensionnel (en principe un DataFrame est une collection de Series, mais pas que)

## Création Series

In [4]:
s=pd.Series([1,5,np.nan,6,10])

In [5]:
s

0     1.0
1     5.0
2     NaN
3     6.0
4    10.0
dtype: float64

## Creation DataFrame
### A partir d'un dict

In [6]:
data={'apple':[3,2,0,1],'orange':[0,1,2,3]}
purchases=pd.DataFrame(data)

In [7]:
purchases

   apple  orange
0      3       0
1      2       1
2      0       2
3      1       3

In [8]:
purchases.loc[0]

apple     3
orange    0
Name: 0, dtype: int64

Observant l'index (il est généré par défaut)

In [9]:
purchases.index

RangeIndex(start=0, stop=4, step=1)

Changeons l'index:

In [12]:
purchases=pd.DataFrame(data,index=['june','rober','alex','lea'])
purchases

       apple  orange
june       3       0
rober      2       1
alex       0       2
lea        1       3

In [13]:
purchases.loc['alex']

apple     0
orange    2
Name: alex, dtype: int64

In [14]:
purchases.index

Index(['june', 'rober', 'alex', 'lea'], dtype='object')

### Autres  exemples de création DataFrame

In [18]:
dates=pd.date_range("20220408",periods=7)

In [19]:
df1=pd.DataFrame(np.random.randn(7,4),index=dates,columns=list('ABCD'))
df1

                   A         B         C         D
2022-04-08 -2.324487  0.508933  1.238655 -0.446246
2022-04-09 -0.469618 -0.863750 -0.053597  0.086050
2022-04-10 -0.249495  0.263221 -1.191146  1.416810
2022-04-11 -1.332763 -0.770449 -0.858106  0.512450
2022-04-12 -0.666713  0.751512 -0.567086  1.437696
2022-04-13 -1.265946 -1.726594  0.129374  0.228248
2022-04-14 -0.773285 -0.264482  1.272982  0.944015

In [22]:
df2=pd.DataFrame({
    "A":1.0,
    "B":pd.Timestamp("20220408"),
    "C":pd.Series(1,index=list(range(4)),dtype="float32"),
    "D":np.array([3]*4,dtype='int32'),
    "E":pd.Categorical(["test","train","test","train"]),
    "F":"foo"
})

In [23]:
df2

     A          B    C  D      E    F
0  1.0 2022-04-08  1.0  3   test  foo
1  1.0 2022-04-08  1.0  3  train  foo
2  1.0 2022-04-08  1.0  3   test  foo
3  1.0 2022-04-08  1.0  3  train  foo

In [25]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

# Importer et exporter des donnees
## à partir de csv
```
df = pd.read_csv('Nom_ou_URL_duFichierCsv')
```
## A partir de json
```
df = pd.read_json('Nom_ou_URL_duFichierjson')
```
## A partir d'excel
```
df = pd.to_excel('Nom_ou_URL_duFichierxlsx", sheet_name="Sheet1")
```
## A partir sqlite 
```
import sqlite3
con = sqlite3.connect("database.db")
df = pd.read_sql_query("SELECT * FROM nameTable", con)
df
```

**Bien évidement  la demarche inverse est possible grace à :**

```
df.to_csv('new_Nom_ou_URL_duFichierCsv')

df.to_json('Nom_ou_URL_duFichierjson')

df.to_sql('new_Name_of_SQL_table', con)
```

In [26]:
df = pd.read_csv('http://chendeb.free.fr/iris.data', names=['sl', 'sw', 'pl', 'pw', 'label'])

In [27]:
import os
os.getcwd()

'c:\\Users\\alex2\\OneDrive\\Documents\\Mastercamp\\TD4'

# Explorer les données

Affichage index

Affichage colonnes

Stat Rapide

voir aussi mean(), mean(1), max...

Transposé des données

## Acces et selection

### Selection d'une colonne

### selection de lignes par slicing

### Selection par label

### Selection multi axes

### Selection par position

Slicing comme numpy/Python

### Boolean indexing

## Données manquantes

## Tri

### Tri selon l'index

### Tri selon les données

## Enlever les redondances

In [ ]:
)

### **inplace** keyword argument  et **keep**

## groupby

## value_counts

## Creez nouvelle colonne

renommer les colonnes

# Plot

In [ ]:
import matplotlib.pyplot as plt

Plotting using Seaborn

In [ ]:
import seaborn as sns


# style used as a theme of graph
# for example if we want black
# graph with grid then write "darkgrid"
sns.set_style("whitegrid")

# sepal_length, petal_length are iris
# feature data height used to define
# Height of graph whereas hue store the
# class of iris dataset.
sns.FacetGrid(df, hue ="label",
			height = 6).map(plt.scatter,
							'sl',
							'pl').add_legend()